  name: "Security & Privacy"
  description: |
    This section contains recommendations for configurable options under the Security & Privacy panel.

    Additional privacy preference information form Apple
      https://support.apple.com/en-gb/guide/security/welcome/web