id: cissecurity_firewall_application_rules
title: "Review Application Firewall Rules"
discussion: |
  [discrete]
  ==== Description:
  A firewall is a piece of software that blocks unwanted incoming connections to a system. Apple has posted general documentation about the application firewall.
  
  http://support.apple.com/en-us/HT201642
  
  A computer should have a limited number of applications open to incoming connectivity.
  
  [discrete]
  ==== Rationale:
  A firewall minimizes the threat of unauthorized users from gaining access to your system while connected to a network or the Internet. Which applications are allowed access to accept incoming connections through the firewall is important to understand.
  
  [discrete]
  ==== Audit:
check: |
  /usr/libexec/ApplicationFirewall/socketfilterfw --listapps | grep ALF | awk '{print $7}'
result:
  integer: 0
fix: |
  Configuration profile - payload > com.apple.security.firewall > Applications > Array > BundleID=com.apple.app > Allowed=false
references:
  cce:
    - CCE-85427-3
  cci: 
    - CCI-000366
  800-53r4: 
    - AC-4
    - AC-6(1)
    - AC-19
    - SC-7
    - CM-7
    - SC-7(12)
  srg:
    - SRG-OS-000480-GPOS-00232
  disa_stig: 
    - APPL-11-005050
  800-171r2:
    - 3.1.3
    - 3.1.5
    - 3.1.18
    - 3.4.6
    - 3.13.1
    - 3.13.2
    - 3.13.5
  custom:
    CIS:
    - 2.5.3 Review Application Firewall Rules (Manual)
    - Level 1
macOS:
  - "11.0"
tags:
  - CIS-Benchmark
  - CIS-Benchmark-L1
severity: "medium"
mobileconfig: false
mobileconfig_info: